* BSIDES Notes
  
** Scenarios

*** IoT "Nuke the Fridge"

    Based on the Silicon Valley finale, users must access a raspberry pi-powered 'smart fridge' located in the CTF hall. When the challenge is completed
    the fridge screen will display a series of gifs. To keep costs down, the 'smart fridge' can just be a monitor mounted on an old fridge.

*** Reversing "Zork"

    CTF Players are provided with a simple adventure game written in C, but the game is impossibly difficult. Players must use reversing skills 
    to get past certain challenges within the adventure game in order to capture the flags.

    Example: A dragon that is unslayable except for casting a certain spell. The words to the spell are found by using Redare2 to get a list
    of spells from the game's code.

*** OSINT "Who is John Doe?"

    Create a fake person online, w/ twitter, reddit, facebook, etc. Have a challenge relating to using OSINT to find this person's Security Questions, or maybe
    ultimately lead to their github account to find sourcecode for a reversing/exploit challenge.

    Example: Players use SQL injection to get a list of accounts on a website. One of the accounts looks interesting. A google search of the name
    leads to a twitter account where there is some kind of clue that might lead to a facebook account. The profile picture has a laptop
    in the background that is logged into a github account. The github contains another clue, etc. Like an ARG.

*** TV Station from Hackers
    
    Use SQL injection to 'change the channel' playing on an online TV station.


** Half-Baked Ideas

   a webserver running on a Commodore 64 (I have a commodore 64 running a web server)
   an IOT Lock (maybe holding an actual flag?)
   a smart gun (Airsoft)
   Something involving an AI (Tensorflow/Keras/Theanos+Flask)
   Movies/TV Theme?
